[package]
name = "spectrometer"
version = "0.1.0"
authors = ["Gabriele Bianchet-David <gbianchetdavid@ebsco.com>"]
edition = "2018"

[dependencies]
winapi = {version = "0.3.7", features = ["processthreadsapi", "sysinfoapi", "impl-debug", "fileapi", "winbase", "lmcons", "std"]}